import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My first next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body >
        <div>
        <h3 style={{color:'wheat'}}>page header</h3>
        </div>
        {children}
        <div>
        <h3 style={{color:'wheat'}}>page footer</h3>
        </div>
        </body>
    </html>
  );
} 
